const WIKI_CONFIG={repository:"https://github.com/SpeedFireF/sosedi",branch:"main",catalogPath:"data/articles.json"};
const state={articles:[],currentArticle:null};
const ids=["article","article-body","article-title","article-description","article-kicker","article-categories","breadcrumbs","category-nav","close-directory","directory-panel","edit-link","filter-chips","article-grid","gallery","gallery-section","infobox","loading-state","menu-button","mobile-toc","recent-changes","search-form","search-input","search-results","share-button","sidebar","sidebar-backdrop","theme-button","toc-list","updated-at","bottom-grid","all-pages-button","toast"];
const el=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
const slugify=value=>value.toLowerCase().trim().replace(/[^a-zа-яё0-9]+/gi,"-").replace(/^-|-$/g,"");

function inlineMarkdown(text){return escapeHtml(text).replace(/!\[([^\]]*)\]\(([^)]+)\)/g,'<img src="$2" alt="$1" loading="lazy">').replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>')}
function renderMarkdown(markdown){
  const lines=markdown.replace(/\r/g,"").split("\n"),html=[];let paragraph=[],listType=null,quote=[];
  const flushParagraph=()=>{if(paragraph.length)html.push(`<p>${inlineMarkdown(paragraph.join(" "))}</p>`);paragraph=[]};
  const closeList=()=>{if(listType)html.push(`</${listType}>`);listType=null};
  const flushQuote=()=>{if(quote.length)html.push(`<blockquote><p>${inlineMarkdown(quote.join(" "))}</p></blockquote>`);quote=[]};
  for(const rawLine of lines){const line=rawLine.trim(),heading=line.match(/^(#{2,3})\s+(.+)$/),list=line.match(/^([-*]|\d+\.)\s+(.+)$/);
    if(!line){flushParagraph();closeList();flushQuote();continue}
    if(heading){flushParagraph();closeList();flushQuote();const level=heading[1].length,id=slugify(heading[2]);html.push(`<h${level} id="${id}">${inlineMarkdown(heading[2])}</h${level}>`)}
    else if(line.startsWith("> ")){flushParagraph();closeList();quote.push(line.slice(2))}
    else if(list){flushParagraph();flushQuote();const wanted=list[1]==="-"||list[1]==="*"?"ul":"ol";if(listType!==wanted){closeList();html.push(`<${wanted}>`);listType=wanted}html.push(`<li>${inlineMarkdown(list[2])}</li>`)}
    else{closeList();flushQuote();paragraph.push(line)}
  }flushParagraph();closeList();flushQuote();return html.join("\n")
}
async function loadWiki(){try{const response=await fetch(WIKI_CONFIG.catalogPath);if(!response.ok)throw Error("catalog");state.articles=await response.json();renderNavigation();renderRecentChanges();await loadArticle(new URLSearchParams(location.search).get("page")||"main")}catch(error){el["loading-state"].innerHTML="<p>Не удалось загрузить энциклопедию. Откройте её через Live Server или GitHub Pages.</p>";console.error(error)}}
async function loadArticle(slug){const item=state.articles.find(article=>article.slug===slug)||state.articles[0];if(!item)return;state.currentArticle=item;el["loading-state"].hidden=false;el.article.hidden=true;el["directory-panel"].hidden=true;el["bottom-grid"].hidden=false;try{const response=await fetch(item.file);if(!response.ok)throw Error("article");renderArticle(item,await response.text());document.title=`${item.title} — Соседи`;history.replaceState({},"",`${location.pathname}?page=${item.slug}`)}catch(error){el["loading-state"].innerHTML="<p>Статья не найдена или пока недоступна.</p>";console.error(error);return}el["loading-state"].hidden=true;el.article.hidden=false}
function renderArticle(item,markdown){el["article-kicker"].textContent=item.type||"Статья энциклопедии";el["article-title"].textContent=item.title;el["article-description"].textContent=item.description;el["article-body"].innerHTML=renderMarkdown(markdown);el.breadcrumbs.innerHTML=`<a href="?page=main">Соседи</a><span>›</span><span>${escapeHtml(item.title)}</span>`;el["edit-link"].href=`${WIKI_CONFIG.repository}/edit/${WIKI_CONFIG.branch}/${item.file}`;el["updated-at"].textContent=`Последнее обновление: ${formatDate(item.updated)}`;el["article-categories"].innerHTML=item.categories.map(category=>`<button class="category-chip" data-category="${escapeHtml(category)}">${escapeHtml(category)}</button>`).join("");renderInfobox(item);renderGallery(item.gallery||[]);renderToc()}
function renderInfobox(item){if(!item.infobox){el.infobox.hidden=true;return}el.infobox.hidden=false;const rows=Object.entries(item.infobox.fields).map(([key,value])=>`<div class="infobox-row"><dt>${escapeHtml(key)}</dt><dd>${escapeHtml(value)}</dd></div>`).join("");el.infobox.innerHTML=`<img class="infobox-image" src="${item.infobox.image}" alt="${escapeHtml(item.infobox.imageAlt)}"><h2 class="infobox-title">${escapeHtml(item.infobox.title)}</h2><dl>${rows}</dl>`}
function renderGallery(gallery){el["gallery-section"].hidden=!gallery.length;el.gallery.innerHTML=gallery.map(image=>`<figure><img src="${image.src}" alt="${escapeHtml(image.alt)}" loading="lazy"><figcaption>${escapeHtml(image.caption)}</figcaption></figure>`).join("")}
function renderToc(){const headings=[...el["article-body"].querySelectorAll("h2")],links=headings.map(heading=>`<li><a href="#${heading.id}">${heading.textContent}</a></li>`).join("");el["toc-list"].innerHTML=links;el["mobile-toc"].innerHTML=headings.length?`<details><summary>Содержание</summary><ol>${links}</ol></details>`:""}
function getCategories(){return[...new Set(state.articles.flatMap(article=>article.categories))].sort((a,b)=>a.localeCompare(b,"ru"))}
function renderNavigation(){el["category-nav"].innerHTML=getCategories().map(category=>`<button class="nav-link" data-category="${escapeHtml(category)}"><span aria-hidden="true">◇</span>${escapeHtml(category)}</button>`).join("")}
function showDirectory(category="Все"){el.article.hidden=true;el["loading-state"].hidden=true;el["bottom-grid"].hidden=true;el["directory-panel"].hidden=false;el.breadcrumbs.innerHTML='<a href="?page=main">Соседи</a><span>›</span><span>Все страницы</span>';el["filter-chips"].innerHTML=["Все",...getCategories()].map(item=>`<button class="filter-chip ${item===category?"active":""}" data-category="${escapeHtml(item)}">${escapeHtml(item)}</button>`).join("");const filtered=category==="Все"?state.articles:state.articles.filter(article=>article.categories.includes(category));el["article-grid"].innerHTML=filtered.map(article=>`<a class="article-card" href="?page=${article.slug}"><h3>${escapeHtml(article.title)}</h3><p>${escapeHtml(article.description)}</p><span class="category-chip">${escapeHtml(article.categories[0])}</span></a>`).join("")||'<p class="empty-search">В этой категории пока нет статей.</p>';closeSidebar()}
function renderRecentChanges(){el["recent-changes"].innerHTML=[...state.articles].sort((a,b)=>b.updated.localeCompare(a.updated)).slice(0,3).map(article=>`<a class="change-item" href="?page=${article.slug}"><span class="change-icon">${escapeHtml(article.title[0])}</span><span><strong>${escapeHtml(article.title)}</strong><small>${escapeHtml(article.change||"Обновлена статья")}</small></span><time datetime="${article.updated}">${formatDate(article.updated,true)}</time></a>`).join("")}
function formatDate(date,short=false){return new Intl.DateTimeFormat("ru-RU",short?{day:"numeric",month:"short"}:{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${date}T12:00:00`))}
function searchArticles(query){const normalized=query.trim().toLocaleLowerCase("ru");if(!normalized){el["search-results"].hidden=true;return}const matches=state.articles.filter(article=>[article.title,article.description,...article.categories,...(article.keywords||[])].join(" ").toLocaleLowerCase("ru").includes(normalized)).slice(0,7);el["search-results"].innerHTML=matches.length?matches.map(article=>`<a class="search-result" href="?page=${article.slug}"><strong>${escapeHtml(article.title)}</strong><small>${escapeHtml(article.description)}</small></a>`).join(""):'<div class="empty-search">Ничего не найдено</div>';el["search-results"].hidden=false}
function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem("wiki-theme",theme);document.querySelector('meta[name="theme-color"]').content=theme==="dark"?"#11171b":"#f3f5f7"}
function toggleSidebar(){const open=el.sidebar.classList.toggle("open");el["sidebar-backdrop"].classList.toggle("open",open);el["menu-button"].setAttribute("aria-expanded",open)}function closeSidebar(){el.sidebar.classList.remove("open");el["sidebar-backdrop"].classList.remove("open");el["menu-button"].setAttribute("aria-expanded","false")}function toast(message){el.toast.textContent=message;el.toast.classList.add("visible");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.toast.classList.remove("visible"),2200)}
el["search-input"].addEventListener("input",event=>searchArticles(event.target.value));el["search-form"].addEventListener("submit",event=>{event.preventDefault();el["search-results"].querySelector("a")?.click()});el["theme-button"].addEventListener("click",()=>applyTheme(document.documentElement.dataset.theme==="dark"?"light":"dark"));el["menu-button"].addEventListener("click",toggleSidebar);el["sidebar-backdrop"].addEventListener("click",closeSidebar);el["all-pages-button"].addEventListener("click",()=>showDirectory());el["close-directory"].addEventListener("click",()=>loadArticle(state.currentArticle?.slug||"main"));el["share-button"].addEventListener("click",async()=>{try{await navigator.clipboard.writeText(location.href);toast("Ссылка скопирована")}catch{toast("Не удалось скопировать ссылку")}});
document.addEventListener("click",event=>{if(!el["search-form"].contains(event.target))el["search-results"].hidden=true;const category=event.target.closest("[data-category]")?.dataset.category;if(category)showDirectory(category)});document.addEventListener("keydown",event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();el["search-input"].focus();el["search-form"].classList.add("open")}if(event.key==="Escape"){el["search-results"].hidden=true;closeSidebar()}});
applyTheme(localStorage.getItem("wiki-theme")||(matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"));loadWiki();
